# Generated by Django 5.2.7 on 2025-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='fecha_eliminacion_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_eliminacion_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
