# Generated by Django 5.2.7 on 2025-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_apellidos_alter_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
