# Generated by Django 5.2.7 on 2025-11-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_otp_fecha_eliminacion_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='fecha_eliminacion_temp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_eliminacion_temp',
        ),
    ]
