# Generated by Django 5.2.7 on 2025-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_otp_fecha_eliminacion_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha eliminacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha eliminacion'),
        ),
    ]
